github: [Repository metadata]
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: "1..2"
highlighter: rouge
permalink: pretty

exclude: ['README.md']

gems:
- jekyll-sitemap

project_title: KLEE
current_version: 1.3.0
repository: https://github.com/klee/klee

# This variable controls changes the behaviour of the banner in
# `_includes/version_warning.md`. When generating documentation
# for a release this should be set to true.
is_release: false
